# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be2ca0e22b7084d40cf3f496a431d29b"
name = "iani-configurator"
handle = "iani-configurator-1"
application_url = "https://iani-configurator-1.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# write_draft_orders needed for custom pricing at checkout
scopes = "read_products,write_products,write_draft_orders"

[auth]
redirect_urls = ["https://iani-configurator-1.onrender.com/auth/callback", "https://iani-configurator-1.onrender.com/auth/shopify/callback", "https://iani-configurator-1.onrender.com/api/auth/callback"]

[pos]
embedded = false
